name: Deploy V4 Site

on:
  push:
    branches: [main]
    paths:
      - 'packages/vant/docs/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.repository == 'youzan/vant'
    runs-on: macos-15
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5
        with:
          ref: 'main'

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force 
          corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: '22.21.1'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Site
        run: npm run build:site

      - name: Deploy for GitHub ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.7.4
        with:
          branch: gh-pages
          folder: packages/vant/site-dist
          token: ${{ secrets.VANT_UI_TOKEN }}
          repository-name: vant-ui/vant-ui.github.io
          target-folder: vant
          # enable single-commit to reduce the repo size
          single-commit: true
          clean: true
          clean-exclude: |
            1.x/*
            1.x/**/*
            next/*
            next/**/*
            v1/*
            v1/**/*
            v2/*
            v2/**/*
            v3/*
            v3/**/*
            v4/*
            v4/**/*
            vant-use/*
            vant-use/**/*
