name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  reply-labeled:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'ğŸ‘ PR welcome' || github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to `main` branch, fill the [Pull Request Template](https://github.com/vant-ui/vant/blob/main/.github/PULL_REQUEST_TEMPLATE.md) here, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæˆ‘ä»¬å®Œå…¨åŒæ„ä½ çš„æè®®/åé¦ˆï¼Œæ¬¢è¿ç›´æ¥åœ¨æ­¤ä»“åº“ [åˆ›å»ºä¸€ä¸ª Pull Request](https://help.github.com/en/articles/creating-a-pull-request) æ¥è§£å†³è¿™ä¸ªé—®é¢˜ã€‚è¯·å°† Pull Request å‘åˆ° `main` åˆ†æ”¯ï¼ŒåŠ¡å¿…å¡«å†™ Pull Request å†…çš„[é¢„è®¾æ¨¡æ¿](https://github.com/vant-ui/vant/blob/main/.github/PULL_REQUEST_TEMPLATE.md)ï¼Œæä¾›æ”¹åŠ¨æ‰€éœ€ç›¸åº”çš„ changelogã€TypeScript å®šä¹‰ã€æµ‹è¯•ç”¨ä¾‹ã€æ–‡æ¡£ç­‰ï¼Œå¹¶ç¡®ä¿ CI é€šè¿‡ï¼Œæˆ‘ä»¬ä¼šå°½å¿«è¿›è¡Œ Reviewï¼Œæå‰æ„Ÿè°¢å’ŒæœŸå¾…æ‚¨çš„è´¡çŒ®ã€‚

      - name: need reproduce
        if: github.event.label.name == 'need reproduce'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide an online reproduction demo by clicking this [link](https://codesandbox.io/s/vant-3-issue-template-8fuq5o) or a minimal GitHub repository. Issues marked with `need reproduce` will be closed if they have no activity within 3 days.

            ä½ å¥½ @${{ github.event.issue.user.login }}, æˆ‘ä»¬éœ€è¦ä½ æä¾›ä¸€ä¸ªåœ¨çº¿çš„é‡ç°å®ä¾‹ä»¥ä¾¿äºæˆ‘ä»¬å¸®ä½ æ’æŸ¥é—®é¢˜ã€‚å¯ä»¥é€šè¿‡ç‚¹å‡» [æ­¤å¤„](https://codesandbox.io/s/vant-3-issue-template-8fuq5o) åˆ›å»ºæˆ–è€…æä¾›ä¸€ä¸ªæœ€å°åŒ–çš„ GitHub ä»“åº“ã€‚3 å¤©å†…æœªè·Ÿè¿›æ­¤ issue å°†ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚

      - name: question
        if: github.event.label.name == 'question'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment, close-issue'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, we use GitHub issues to trace bugs or discuss plans of Vant. So, please don't ask usage questions here. You can try to open a new discussion in [vant discussions](https://github.com/vant-ui/vant/discussions), select `Q&A` to ask questions.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼ŒVant Issue æ¿å—æ˜¯ç”¨äº bug åé¦ˆä¸éœ€æ±‚è®¨è®ºçš„åœ°æ–¹ã€‚è¯·å‹¿åœ¨è¿™é‡Œè¯¢é—®å¦‚ä½•ä½¿ç”¨ç­‰ç›¸å…³é—®é¢˜ï¼Œä½ å¯ä»¥è¯•ç€åœ¨ [vant discussions](https://github.com/vant-ui/vant/discussions) æ–°å¼€ä¸€ä¸ª discussionï¼Œé€‰æ‹© `Q&A` ç±»åˆ«è¿›è¡Œæé—®ã€‚

      - name: 2.x
        if: github.event.label.name == '2.x'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment, close-issue'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }}. Current version (2.x) is off the maintenance period. We will only fix critical bugs. This issue will be auto closed.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œå½“å‰ç‰ˆæœ¬ï¼ˆ2.xï¼‰å·²ç»è¿‡äº†ç»´æŠ¤æœŸã€‚æˆ‘ä»¬ä»…ä¼šä¿®å¤é‡è¦ bugã€‚å½“å‰ issue ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚

      - name: invalid
        if: github.event.label.name == 'invalid'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment, close-issue'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not conform to our issue requirements.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä¸ºäº†èƒ½å¤Ÿè¿›è¡Œé«˜æ•ˆæ²Ÿé€šï¼Œæˆ‘ä»¬å¯¹ issue æœ‰ä¸€å®šçš„æ ¼å¼è¦æ±‚ï¼Œä½ çš„ issue å› ä¸ºä¸ç¬¦åˆè¦æ±‚è€Œè¢«è‡ªåŠ¨å…³é—­ã€‚
